'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM3")>  _
        Public Property ArduinoComPort() As String
            Get
                Return CType(Me("ArduinoComPort"),String)
            End Get
            Set
                Me("ArduinoComPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("35")>  _
        Public Property RefreshRate() As Byte
            Get
                Return CType(Me("RefreshRate"),Byte)
            End Get
            Set
                Me("RefreshRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("63")>  _
        Public Property GPowerForMin() As Integer
            Get
                Return CType(Me("GPowerForMin"),Integer)
            End Get
            Set
                Me("GPowerForMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property ACRpm1() As Single
            Get
                Return CType(Me("ACRpm1"),Single)
            End Get
            Set
                Me("ACRpm1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.64")>  _
        Public Property ACRpm2() As Single
            Get
                Return CType(Me("ACRpm2"),Single)
            End Get
            Set
                Me("ACRpm2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("250")>  _
        Public Property ACMaxSpeed() As Integer
            Get
                Return CType(Me("ACMaxSpeed"),Integer)
            End Get
            Set
                Me("ACMaxSpeed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ACSlip() As Short
            Get
                Return CType(Me("ACSlip"),Short)
            End Get
            Set
                Me("ACSlip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ACPitch() As Single
            Get
                Return CType(Me("ACPitch"),Single)
            End Get
            Set
                Me("ACPitch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ACRoll() As Single
            Get
                Return CType(Me("ACRoll"),Single)
            End Get
            Set
                Me("ACRoll") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ACAccel() As Short
            Get
                Return CType(Me("ACAccel"),Short)
            End Get
            Set
                Me("ACAccel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ACTurn() As Short
            Get
                Return CType(Me("ACTurn"),Short)
            End Get
            Set
                Me("ACTurn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property vJoyId() As Byte
            Get
                Return CType(Me("vJoyId"),Byte)
            End Get
            Set
                Me("vJoyId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PitchOffset() As Single
            Get
                Return CType(Me("PitchOffset"),Single)
            End Get
            Set
                Me("PitchOffset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property RollOffset() As Single
            Get
                Return CType(Me("RollOffset"),Single)
            End Get
            Set
                Me("RollOffset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("290")>  _
        Public Property AccelMin() As Integer
            Get
                Return CType(Me("AccelMin"),Integer)
            End Get
            Set
                Me("AccelMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("850")>  _
        Public Property AccelMax() As Integer
            Get
                Return CType(Me("AccelMax"),Integer)
            End Get
            Set
                Me("AccelMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
        Public Property BrakeMin() As Integer
            Get
                Return CType(Me("BrakeMin"),Integer)
            End Get
            Set
                Me("BrakeMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("800")>  _
        Public Property BrakeMax() As Integer
            Get
                Return CType(Me("BrakeMax"),Integer)
            End Get
            Set
                Me("BrakeMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
        Public Property ClutchMin() As Integer
            Get
                Return CType(Me("ClutchMin"),Integer)
            End Get
            Set
                Me("ClutchMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("800")>  _
        Public Property ClutchMax() As Integer
            Get
                Return CType(Me("ClutchMax"),Integer)
            End Get
            Set
                Me("ClutchMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MouseSteering() As Integer
            Get
                Return CType(Me("MouseSteering"),Integer)
            End Get
            Set
                Me("MouseSteering") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("780")>  _
        Public Property WheelDampFactor() As Integer
            Get
                Return CType(Me("WheelDampFactor"),Integer)
            End Get
            Set
                Me("WheelDampFactor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8.75")>  _
        Public Property WheelSensitivity() As Single
            Get
                Return CType(Me("WheelSensitivity"),Single)
            End Get
            Set
                Me("WheelSensitivity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property WheelDead() As Integer
            Get
                Return CType(Me("WheelDead"),Integer)
            End Get
            Set
                Me("WheelDead") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Edited() As Boolean
            Get
                Return CType(Me("Edited"),Boolean)
            End Get
            Set
                Me("Edited") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property WheelPowerGama() As Single
            Get
                Return CType(Me("WheelPowerGama"),Single)
            End Get
            Set
                Me("WheelPowerGama") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("110")>  _
        Public Property WheelPowerForMin() As Integer
            Get
                Return CType(Me("WheelPowerForMin"),Integer)
            End Get
            Set
                Me("WheelPowerForMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.1")>  _
        Public Property WheelPowerFactor() As Single
            Get
                Return CType(Me("WheelPowerFactor"),Single)
            End Get
            Set
                Me("WheelPowerFactor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public Property SpeedGama() As Single
            Get
                Return CType(Me("SpeedGama"),Single)
            End Get
            Set
                Me("SpeedGama") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.8")>  _
        Public Property ACJump() As Single
            Get
                Return CType(Me("ACJump"),Single)
            End Get
            Set
                Me("ACJump") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("23")>  _
        Public Property SpeedMinPower() As Integer
            Get
                Return CType(Me("SpeedMinPower"),Integer)
            End Get
            Set
                Me("SpeedMinPower") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property AccelGama() As Single
            Get
                Return CType(Me("AccelGama"),Single)
            End Get
            Set
                Me("AccelGama") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property BrakeGama() As Single
            Get
                Return CType(Me("BrakeGama"),Single)
            End Get
            Set
                Me("BrakeGama") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ClutchGama() As Single
            Get
                Return CType(Me("ClutchGama"),Single)
            End Get
            Set
                Me("ClutchGama") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WheelMinInput() As Integer
            Get
                Return CType(Me("WheelMinInput"),Integer)
            End Get
            Set
                Me("WheelMinInput") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property ACMinSpeed() As Integer
            Get
                Return CType(Me("ACMinSpeed"),Integer)
            End Get
            Set
                Me("ACMinSpeed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("270")>  _
        Public Property GZDistance() As Integer
            Get
                Return CType(Me("GZDistance"),Integer)
            End Get
            Set
                Me("GZDistance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("250")>  _
        Public Property GXDistance() As Integer
            Get
                Return CType(Me("GXDistance"),Integer)
            End Get
            Set
                Me("GXDistance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property GMinDiff() As Integer
            Get
                Return CType(Me("GMinDiff"),Integer)
            End Get
            Set
                Me("GMinDiff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property GMaxDiff() As Integer
            Get
                Return CType(Me("GMaxDiff"),Integer)
            End Get
            Set
                Me("GMaxDiff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("75")>  _
        Public Property GMaxScrewUp() As Integer
            Get
                Return CType(Me("GMaxScrewUp"),Integer)
            End Get
            Set
                Me("GMaxScrewUp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("65")>  _
        Public Property GMaxScrewDown() As Integer
            Get
                Return CType(Me("GMaxScrewDown"),Integer)
            End Get
            Set
                Me("GMaxScrewDown") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CVJoy.My.MySettings
            Get
                Return Global.CVJoy.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
